# .streamlit/secrets.toml
# Configuration file for API keys and secrets

# Qdrant Cloud Vector Database
# Sign up for free at: https://cloud.qdrant.io/
QDRANT_URL = ""
QDRANT_API_KEY = ""

# Hugging Face API for LLM
# Get free API key at: https://huggingface.co/settings/tokens
HUGGINGFACE_API_KEY = ""

GROQ_API_KEY = ""

# Instructions:
# 1. Create a Qdrant Cloud account (free tier available)
# 2. Create a cluster and get your URL and API key
# 3. Create a Hugging Face account and generate an API token
# 4. Replace the placeholder values above with your actual keys
# 5. Make sure this file is in the .streamlit/ directory